### ISSUE TITLE
Review commands

### ISSUE THREAD

**Issue by e0003823** [CS2103JAN2017-W09-B3/main#44]

**Comment by e0003823** [comment]
1) if another by is hit, then the first by is part of task name, repeat check from next by. 2) if no next by, check if date follows, if yes, take it as keyword. 3) if date does not follow, treat by as part of name and the task is floating

**Comment by nnamon** [comment]
Completed in Commit 3b06f6ab686f375d4f39e242bd327f1eb0c7851f.
