### ISSUE TITLE
Handle Ambiguous Commands

### ISSUE THREAD

**Issue by nnamon** [CS2103JAN2017-W09-B3/main#84]

**Comment by e0003823** [comment]
Checked, Check, Complete / Unchecked, Uncheck, Undone, Uncomplete, Incomplete
From, After, On / To, By
Find, Search, "default"
Edit, Change
Delete, Del, Remove

**Comment by nnamon** [comment]
Command aliases are done and are in v0.5rc-HandleAmbigiousCommands.

Whats left to do:
Modify regex for add/edit to use multiple command words.
Modify regex for edit to accept "" blank task names.
